### ISSUE TITLE
can not use with rails 4.2

### ISSUE THREAD

**Issue by bingxie** [wojtekmach/minitest-capybara#14]
My application:
rails 4.2.4
capybara 2.5.0
minitest 5.8.2

**Comment by wojtekmach** [comment]
@bingxie sorry for a late reply. I'd need more information to help you out, however this gem should be already working on these versions of libraries. See: https://github.com/wojtekmach/minitest-capybara-example

Please re-open if this is still an issue with some more information and ideally a reproducible test. Thanks!
