### ISSUE TITLE
Clarify what extra functionality this gem provides

### ISSUE THREAD

**Issue by twalpole** [wojtekmach/minitest-capybara#22]
In Capybara 2.x this gem provided much needed support for mintest assertions.  Since Capybara added its own minitest assertions - https://github.com/teamcapybara/capybara/blob/master/lib/capybara/minitest.rb and https://github.com/teamcapybara/capybara/blob/master/lib/capybara/minitest/spec.rb - it's much less clear what added functionality this gem provides.

**Comment by wojtekmach** [comment]
@twalpole it's fantastic to see Mintiest support upstream, I didn't know as I haven't been paying attention for a few years. In that case the gem doesn't make sense to exist anymore, I'll add deprecation notice and point people upstream. Thank you!

**Comment by twalpole** [comment]
@wojtekmach You're welcome, I just wanted to make sure this gem wasn't providing some functionality that hadn't been added upstream.
